/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PaybackAndroid;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
//import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.testng.annotations.*;

import com.google.common.collect.ImmutableMap;

import io.appium.java_client.android.AndroidDeviceActionShortcuts;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.android.AndroidKeyCode;
import io.appium.java_client.ios.IOSDriver;

public class PaybackTest {
	WebDriver driver;
	URL appiumUrl;
	File app;
	
	@BeforeClass
	public void setUp() throws MalformedURLException{
		appiumUrl = new URL("http://localhost:4723/wd/hub");
		ClassLoader classLoader = getClass().getClassLoader();
		File file = new File(classLoader.getResource("PAYBACK_Shopping_Rewards_App_13.0.0.13_apkcombo.com.apk").getFile());
		
		//Appium Inspector JSON Info
//		{
//		  "appium:BROWSER_NAME": "Android",
//		  "appium:VERSION": "4.4.2",
//		  "appium:deviceName": "Emulator",
//		  "platformName": "Android",
//		  "appium:app": "C:\\\\Users\\\\Admin\\\\eclipse-workspace\\\\PaybackAndroid\\\\lib\\\\src\\\\test\\\\resources\\\\apps\\\\PAYBACK_ Shopping Rewards App_13.0.0.13_apkcombo.com.apk",
//		  "appium:appPackage": "com.adobe.cq.mobile.payback",
//		  "appium:appActivity": "com.valtech.payback.presentation.ui.activities.MainActivity"
//		}
		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability("unicodeKeyboard", "true");                                     
		capabilities.setCapability("resetKeyboard", "true");
		capabilities.setCapability("BROWSER_NAME", "Android");
		capabilities.setCapability("VERSION", "4.4.2"); 
		capabilities.setCapability("deviceName","Emulator");
		capabilities.setCapability("platformName","Android");
		capabilities.setCapability("app", file.getAbsolutePath());
		capabilities.setCapability("appPackage", "com.adobe.cq.mobile.payback");
		capabilities.setCapability("appActivity","com.valtech.payback.presentation.ui.activities.MainActivity");
		driver = new RemoteWebDriver(appiumUrl, capabilities);
	}

	@Test
	public void testApp() throws Exception {
		driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		//click on profile image at right corner 
		driver.findElement(By.id("com.adobe.cq.mobile.payback:id/profile_img")).click();
		//click on sign in button in the list 
		driver.findElement(By.id("com.adobe.cq.mobile.payback:id/signOutBtn")).click();
		//Enter username 
		driver.findElement(By.id("com.adobe.cq.mobile.payback:id/mobile_number_edt")).sendKeys("9876543210");
		//Enter username
		driver.findElement(By.id("com.adobe.cq.mobile.payback:id/pin_edt")).sendKeys("1234");
		//click on signIn button
		driver.findElement(By.id("com.adobe.cq.mobile.payback:id/linearLayoutSignIn")).click();
		//click on skip button 
		driver.findElement(By.id("com.adobe.cq.mobile.payback:id/skip")).click();
		//click on Menu on the top left 
		driver.findElement(By.id("com.adobe.cq.mobile.payback:id/menu_icon")).click();
		//click on Coupon section
		driver.findElement(By.xpath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/"
				+ "android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/"
				+ "androidx.drawerlayout.widget.DrawerLayout/android.widget.FrameLayout/"
				+ "android.widget.LinearLayout/android.widget.FrameLayout/android.widget.ListView/"
				+ "android.widget.RelativeLayout[9]/android.widget.LinearLayout/android.widget.TextView")).click();
		//click on Search glass
		driver.findElement(By.id("com.adobe.cq.mobile.payback:id/actionEvent")).click();
		//click on "Search Earn" area
		driver.findElement(By.id("com.adobe.cq.mobile.payback:id/search_img")).click();
		//clear the search area
		driver.findElement(By.id("com.adobe.cq.mobile.payback:id/searchTextView")).clear();
		//Eneter burger in  the search area 
		driver.findElement(By.id("com.adobe.cq.mobile.payback:id/searchTextView")).sendKeys("burger");
		//click on search 
		((RemoteWebDriver) driver).executeScript("mobile:performEditorAction", ImmutableMap.of("action", "Search"));
	}

	@AfterClass
	public void teardown(){
		//close the app
		driver.quit();
	}
}

